config/routes.rb
Rails.application.routes.draw do
  resources :albums
  root 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :tracks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/track.rb
class Track < ApplicationRecord
    belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def index
        @albums = Album.all
    end
    def show
        @album = Album.find(params[:id])
        @tracks = @album.tracks
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<div class="row">
  
  <% @albums.each do |album| %>
  <div class="col-md-3">
    <%= link_to album_path(album) do%>
      <div class="thumbnail">
        <img src="<%= album.cover %>">
        <div class="caption">
          <h3 class="title"><%=album.title%></h3>
          <p class="artist"><%=album.artist%></p>
        </div>
      </div>
    <% end %>
  
  </div>
  <% end %>
  
</div>

app/views/albums/show.html.erb
<div class="show row">
  <div class="cover col-md-4"> <%= image_tag(@album.cover) %> </div>

  <div class="col-sm-8">
    <h3 class="album-title">  </h3>
    <p class="album-artist">  </p>

    
  <%= @tracks.each do |f| %>
    <div class="track row">
      <div class="name col-md-8"> <%= f.name %> </div>
      <div class="minutes col-md-4"> <%= f.minutes %> min </div>
    </div>
  <% end %>
    
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BassMusic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img class="logo" src="http://s3.amazonaws.com/codecademy-content/projects/3/bass-music/logo.svg"/>
      </div>
    </div>

    <div class="main">
      <div class="container">

        <%= yield %>
      
      </div>
    </div>

    <div class="footer">
      <div class="container">
        <div class="col-md-2">
          <h3>Bass</h3>
          <ul>
            <li><a href="#">Install</a></li>
            <li><a href="#">Mobile</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>About</h3>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Team</a></li>
            <li><a href="#">Jobs</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>Support</h3>
            <li><a href="#">Help Center</a></li>
            <li><a href="#">Get Started</a></li>  
            <li><a href="#">Contact Us</a></li>
          </ul>
        </div>
        <div class="col-md-2">
          <ul>
            <h3>Community</h3>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Google+</a></li>
          </ul>
        </div>
      </div>
    </div>

  </body>
</html>